### ISSUE TITLE
Palavra chave dos ambientes precisam ser reconfiguradas a cada acesso

### ISSUE THREAD

**Issue by gabrielpetrone** [jotaajunior/blip-addons#28]
Alterei as palavras chaves do ambiente de acordo com meu contrato e funcionou perfeitamente após atualizar a página. Fechei a página e ao voltar a configuração realizada havia se perdido, sendo necessário reconfigurar toda vez que eu retornar pra página.

Após configurar:
![2022-04-26 10_19_22-Blip Portal](https://user-images.githubusercontent.com/11214455/165352367-bfa6e305-47df-418c-b49e-0a8524024c59.png)

Após fechar a aba e voltar ao Portal:
![2022-04-26 13_52_38-](https://user-images.githubusercontent.com/11214455/165352450-76ad3342-0ec5-4d5e-b34b-c11e3b5cbab3.png)

**Comment by jotaajunior** [comment]
Opa, @gabrielpetrone, tudo bem?

Muito obrigado por reportar esse bug! Vamos tentar resolvê-lo e publicar como correção na próxima versão assim que possível.

**Comment by jotaajunior** [comment]
Acredito que esse bug tenha sido resolvido no PR mais recente. Irei publicar a nova versão na Chrome Store e em breve todos devem receber a atualização.

**Comment by gabrielpetrone** [comment]
Sucesso! Fiz novos testes e o que eu havia identificado foi corrigido.
Muito obrigado!
